name: CI/CD Azure Functions Python

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Instalar Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Instalar dependências (Poetry)
        run: poetry install --no-interaction --no-root
      - name: Formatar código com Black
        run: poetry run black .
      - name: Fazer commit e push das alterações de formatação
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git diff --quiet; then
            git commit -am "style: Formata o código com black"
            git push
          else
            echo "Nenhuma alteração de formatação para fazer commit."
          fi
      - name: Checar linting com Flake8
        run: poetry run flake8 .
      - name: Rodar testes
        run: poetry run pytest --cov=src --cov-fail-under=90

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy para Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'cpf-function' # Preencha aqui com o nome EXATO do recurso Azure Functions!
          package: '.'
