name: CI/CD Azure Functions com Poetry

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Instalar dependências
        run: poetry install --no-interaction --no-root

      - name: Rodar testes unitários e cobertura
        run: poetry run pytest --cov=src --cov-report=xml --cov-fail-under=90

      - name: Publicar relatório de cobertura (opcional)
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: false

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Instalar dependências
        run: poetry install --no-interaction --no-root

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy para Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'cpf-function' # Ajuste conforme seu Function App!
          package: '.'
